services:
  db:
    image: postgres:15
    networks:
      - app-network
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - shared_postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      APP_ENV: ${APP_ENV}
      APP_DEBUG: false
      OCTANE_SERVER: frankenphp
      APP_URL: https://flipalara.com

      DB_PORT: 5432
      DB_DATABASE: database
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      APP_KEY: ${APP_KEY}
      AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - db
    networks:
      - app-network

volumes:
  shared_postgres_data:
    external: true

networks:
  app-network:
    external: true
