#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Usage: add_application_name <Application Name> <URL> <Repo Name>"
    return 1
fi

APP_NAME="$1"
APP_URL="$2"
REPO_NAME="$3"

if [ "$(uname)" == "Darwin" ]; then
    # stupid mac
    sed_cmd="sed -i ''"
else
    sed_cmd="sed -i"
fi

git ls-files | grep -v "scripts/add_application_name" | while read -r file; do
    eval "$sed_cmd" \
        -e "s/APP_NAME_PLACEHOLDER/$APP_NAME/g" \
        -e "s/APP_URL_PLACEHOLDER/$APP_URL/g" \
        -e "s/REPO_NAME_PLACEHOLDER/$REPO_NAME/g" \
        "$file"
done
