#!/bin/bash

FEATURE="$1"
FEATURES=$(git ls-remote --heads template | sed 's#.*refs/heads/##')

if [ $# -ne 1 ]; then
    echo "Usage: add_feature $FEATURES"
    return 1
fi

if ! echo "$FEATURES" | grep -q "$FEATURE"; then
    echo "Error: '$FEATURE' is not a valid feature."
    return 1
fi

git fetch template --all
git merge template/"$FEATURE"
composer install

case "$FEATURE" in
"stripe")
    composer require laravel/casher
    php artisan vendor:publish --tag="cashier-migrations"
    php artisan migrate
    php artisan vendor:publish --tag="cashier-config"
    ;;
"oauth")
    composer require laravel/socialite
    php artisan migrate
    ;;
esac
