#!/bin/bash

if [ $# -ne 3 ]; then
    echo "Usage: add_application_name <Application Name> <URL> <Repo Name>"
    return 1
fi

APP_NAME=$1
APP_URL=$2
REPO_NAME=$3

git ls-files | xargs sed -i 's/{{ APP_NAME }}/$APP_NAME/g'
git ls-files | xargs sed -i 's/{{ APP_URL }}/$APP_URL/g'
git ls-files | xargs sed -i 's/{{ REPO_NAME }}/$REPO_NAME/g'

sed -i "s!APP_URL=http://localhost!APP_URL=$APP_URL!" .env

git add resources/js/ApplicationLogo.vue .env.example
git commit -m "add application name"
git push -u origin main
