#!/bin/bash
PROJ_NAME= # TODO

sudo yum install docker -y
sudo service docker start
sudo usermod -a -G docker ec2-user

sudo yum install nginx -y
sudu systemctl start nginx
sudo systemctl enable nginx

sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

/bin/bash -c "$(curl -fsSL https://php.new/install/linux/8.3)"
source ~/.bashrc

composer install

cp .env.example .env
sed -i 's/APP_ENV=local/APP_ENV=production/' .env

php aritsan key:generate
php artisan migrate

# Log out, log back in

sudo yum install certbot python3-certbot-nginx -y
